### ISSUE TITLE
/skipnight yes not working

### ISSUE THREAD

**Issue by markimarc** [mattboy9921/SkipNight#1]
The command /skipnight yes is not working.
The server says the command is unknown :').
/skipnight is working as it should.

**Comment by mattboy9921** [comment]
I'll look into this ASAP. Probably an issue with ACF. Still trying to perfect my implementation.

**Comment by mattboy9921** [comment]
Latest commit should have fixed this. Still not sure how to get command suggestions working. 
#9d07406
