### ISSUE TITLE
Interactive Buttons in /skipnight do not appear to work

### ISSUE THREAD

**Issue by Thatsmusic99** [mattboy9921/SkipNight#13]
Tested using SkipNight 1.5.2 and the latest version of Paper, this being `git-Paper-281 (MC: 1.17.1)`. 

The interactive buttons when using /skipnight do not appear to work to hovering or clicking, as seen here: https://gyazo.com/3299b8e70078f62feb70d5e2cf9a40e4

Am using the default configuration (both config.conf and messages.conf) but if there's any extra information I need to provide or extra testing needed, let me know and I can do that.

**Comment by mattboy9921** [comment]
I can recreate this behavior, I'll be looking into why this is happening.
