### ISSUE TITLE
Paper 1.18 | After Upgrade: Again broken for Chat

### ISSUE THREAD

**Issue by tininet** [mattboy9921/SkipNight#14]
Hello,

After upgrading to 1.18 the Plugin seems to be broken again (chat-wise). You can't klick the Text in the Chat. Everything else seems to work just fine.

**Comment by mattboy9921** [comment]
Can confirm the bug is happening for myself as well. Doing tests to figure out why.

**Comment by mattboy9921** [comment]
@tininet, check out the [new release](https://github.com/mattboy9921/SkipNight/releases/tag/1.5.4) for a version that works with 1.18.

**Comment by tininet** [comment]
Can confirm: Works again on paper1.18#59 - [33ea869].
Thanks mate!
