### ISSUE TITLE
MiniMessage tags appearing in strings

### ISSUE THREAD

**Issue by Roshanxy** [mattboy9921/SkipNight#15]
![upload_2022-1-19_17-21-15](https://user-images.githubusercontent.com/45039943/150595337-a1cdbc5e-87a0-47ed-947c-ec651cb4748d.png)
Deleting the messages.conf file resulted in the problem persisting 

![image](https://user-images.githubusercontent.com/45039943/150595398-d52d5733-dff2-4e82-9a60-5579cf6714c6.png)

**Comment by mattboy9921** [comment]
Just to confirm, you restarted the server after deleting the file?

**Comment by mattboy9921** [comment]
Closing because I have not heard back.
