### ISSUE TITLE
Players can't vote "yes" if they're attacked by phantoms, even if "phantom-support=false"

### ISSUE THREAD

**Issue by ViMaSter** [mattboy9921/SkipNight#16]
Attempting to run this plugin on my server, I noticed, that the `phantom-support=false`-rule is limited to starting new votes:
![image](https://user-images.githubusercontent.com/1689033/157954544-4e649ac6-714d-4cd1-b68e-8ff5f950ca6e.png)

With `phantom-support=false`, players are able to start a vote using `/skipnight`, but, if another player has started the vote and they attempt to vote `YES`, they're unable to do so.

**Comment by mattboy9921** [comment]
Thanks for the PR! I will take a look at this tonight.
