### ISSUE TITLE
Add a world blocker line in config.

### ISSUE THREAD

**Issue by matipoirierg** [mattboy9921/SkipNight#18]
Hi, I have the suggestion to add a line to block certain worlds for the votation since a lot of people have multiple overworlds.

**Comment by mattboy9921** [comment]
That's a good idea. I believe the plugin already is aware of the world the player starts the vote from and it makes sense that only people in the same world should see the vote. I'll take a look into this when I have some time.

**Comment by matipoirierg** [comment]
effectively the plugin does what you mentioned, but I was referring to this: for example, my spawn is a separated overworld and I don't want players to start votations there. Cheers!

**Comment by mattboy9921** [comment]
Ohhh 🤦‍♂️ 

I see what you're saying now. So you could blacklist an overworld type world from being allowed to start a vote. That's actually a lot simpler from what I'm thinking.
