### ISSUE TITLE
Cant change the "[Vote]" text before messages

### ISSUE THREAD

**Issue by itsAudioo** [mattboy9921/SkipNight#19]
as the title says...
Is there a way to change this message and its color. Thanks

**Comment by mattboy9921** [comment]
To change the text shown, you can look for the following field in the `messages.conf` file in the config folder:
```hocon
# Vote text that appears before certain messages.
# (Does not accept color codes)
vote=Vote
```
As for the color, I believe that is hard coded into the plugin.

Let me know if you have any questions!

**Comment by itsAudioo** [comment]
I did, but it stil says [Vote] before messages

**Comment by mattboy9921** [comment]
I can reproduce the issue, I will take a look at this.

**Comment by mattboy9921** [comment]
@audiomaster99, please check out  the [SkipNight 1.6.2 release](https://github.com/mattboy9921/SkipNight/releases/tag/1.6.2) for the fix 😄
