### ISSUE TITLE
Skipnight able to be spammed.

### ISSUE THREAD

**Issue by Braaadley** [mattboy9921/SkipNight#20]
Can we have an option for /skipnight, once it's run, if it's denied, to not be run again for a certain duration? Currently it's heavily affecting my community as the vote will go through, be denied, and the vote will start back up again because the same player or a different player runs the skipnight vote command, again.

**Comment by mattboy9921** [comment]
This sounds like a good feature. I will try to implement this. Should have some time this week.

**Comment by mattboy9921** [comment]
Famous last words I suppose. This is still on my radar, I just have not had the time to look at it.

**Comment by mattboy9921** [comment]
This will be in the next release.
