### ISSUE TITLE
skipnight no bed set issue

### ISSUE THREAD

**Issue by Mentrixx** [mattboy9921/SkipNight#21]
When you do /sn or /sn yes it requires you to sleep in a bed even though you already have.
You then sleep in a bed, then after sometime it will state that you need to sleep in a bed again.

Attempting to re-create on purpose hasn't been successful, but when I try not re-create it, it happens all the time.

**Comment by mattboy9921** [comment]
Interesting. The condition to sleep in a bed is looking at the time since last rest value, same one the phantoms use to attack. Are you experiencing phantom spawns when it doesn't allow you to vote even after sleeping?

**Comment by Mentrixx** [comment]
I didn't see the configuration option to ignore Phantoms, sorry about that one! You can delete this if you want :D
