### ISSUE TITLE
Ability to disable vote text that appears before messages

### ISSUE THREAD

**Issue by hilltty** [mattboy9921/SkipNight#22]
```yaml
# 
# Vote text that appears before certain messages.
# (Does not accept color codes)
vote="Vote"
```
It would be very nice to add a complete removal feature. Thank you!

**Comment by hilltty** [comment]
Also, an alternative can be a complete format setting

**Comment by mattboy9921** [comment]
I should be able to make it so the `[Vote]` text can be disabled. Adding a way to fully format things would be more complicated so I may hold off on that.
