### ISSUE TITLE
is it possible to make it so that when you click on the button to start voting, it starts immediately

### ISSUE THREAD

**Issue by Domen-1** [mattboy9921/SkipNight#24]
is it possible to make it so that when you click on the button to start voting, it starts immediately. When I lie down on the bed and press the “start voting” button, a command with the start of voting is written to the chat, is it possible to skip it like that and after pressing the button, the voting starts immediately? Maybe you need to fix a line in the code, or something else?

**Comment by mattboy9921** [comment]
Yes, this is something I have wanted to do for a while. There are two options: suggest command and run command. The former is currently set but I think we agree it should be the latter. I will make this change for the next release.

**Comment by Domen-1** [comment]
when will the next release come out?

**Comment by mattboy9921** [comment]
There is no ETA. Updates will come when they are ready. I do have some API changes to make for commands so it may be soon.

**Comment by Domen-1** [comment]
I'm just launching my server soon (on the 23rd), I wanted not to let the guys down and play right away with convenience)

**Comment by mattboy9921** [comment]
This should be fixed with 47461b3 and will be included in the next release.
