### ISSUE TITLE
possible addition to the plugin

### ISSUE THREAD

**Issue by Domen-1** [mattboy9921/SkipNight#27]
Hello, and it's me again)
I would also like to suggest adding the ability to skip a thunderstorm not at night. In vanilla minecraft, there is such an opportunity.
I would also like to ask how things are going with voting without entering a command, but simply by pressing the select button (yes, no)

**Comment by mattboy9921** [comment]
I was thinking about that the other day. May be possible to add. I will look into it. 

#24 is implemented in code but I haven't finished the release yet. I have been working on setting up a unit test suite to make verifying my implementations faster.

**Comment by Domen-1** [comment]
I have such a not modest question, can you give me this plugin without a unit test? it's just that my players really don't like that the voting takes a very long time and there are constant complaints :(

**Comment by mattboy9921** [comment]
@Domen-1, please check out the latest release here: https://github.com/mattboy9921/SkipNight/releases

The latest update came out yesterday and has the features suggested in this issue and #24 in it. 

*I will also add that generally, you want to avoid discussing multiple issues in a single thread unless they are related.*
