### ISSUE TITLE
night skip bug

### ISSUE THREAD

**Issue by Domen-1** [mattboy9921/SkipNight#29]
When there was no one else on the server but me, I started a vote to skip the night as a team, then quickly moved to the nether, and after that this strip on top broke.

![2023-08-03_23 15 48](https://github.com/mattboy9921/SkipNight/assets/111240419/f0822550-78e0-4ae5-b98f-a4e4ac6bd756)

**Comment by mattboy9921** [comment]
I've also experienced similar but have not been able to nail down the exact conditions this happens in. 

So your condition is: Start vote as only person on server, enter nether, vote bar breaks. 

I'll be playing around with this to figure out the problem.

**Comment by Domen-1** [comment]
I also want to add that when you start voting with the help of the command, and then lie down on the bed, then you skip the night faster vanilla and this strip again lag

**Comment by mattboy9921** [comment]
By that it sounds like there is an issue with the "It is already day" detection.

**Comment by mattboy9921** [comment]
@Domen-1 please check out the beta I just released [here](https://github.com/mattboy9921/SkipNight/releases/tag/1.8.0-beta.1). I believe it might help with this issue.

**Comment by mattboy9921** [comment]
This should be fixed in my testing of the latest beta release.
