### ISSUE TITLE
The only downside to this plugin is that when a vote fails, you can no longer start a new vote until the plugin is reloaded :(

### ISSUE THREAD

**Issue by runcikas** [mattboy9921/SkipNight#31]
The only downside to this plugin is that when a vote fails, you can no longer start a new vote until the plugin is reloaded :(
![image](https://github.com/mattboy9921/SkipNight/assets/84180826/f618fe7e-7509-4887-8a37-6e7c8197f7a0)

**Comment by mattboy9921** [comment]
Yes, this is an issue in the current beta. I've not had the time lately to fix it.

**Comment by runcikas** [comment]
maybe it is possible to somehow write if vote fails plugin resets ?

**Comment by mattboy9921** [comment]
That wouldn't be necessary. There is a condition happening right now where the vote essentially never leaves cooldown. Keep in mind this is a beta release with major rewrites so it is likely for these issues. If you need more stability, the 1.7.0 release likely would be better to use until I get a proper 1.8.0 release out.

**Comment by mattboy9921** [comment]
This should be fixed with the latest beta release in my testing.
