### ISSUE TITLE
Deprecated Event During Startup Warning (Cloud Update)

### ISSUE THREAD

**Issue by enigma072485** [mattboy9921/SkipNight#38]
`WARN22:41:19
[SkipNight]: "SkipNight v1.8.1" has registered a listener for com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent on method "public void net.mattlabs.skipnight.cloud.paper.PaperBrigadierListener.onCommandRegister(com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent<com.destroystokyo.paper.brigadier.BukkitBrigadierCommandSource>)", but the event is Deprecated. "This event has been superseded by the Commands API and will be removed in a future release. Listen to LifecycleEvents.COMMANDS instead."; please notify the authors [mattboy9921 (mattboy9921@aim.com)].`

Getting this during startup.
Purpur Version: 1.20.6-2219-b1464f3 (MC: 1.20.6)*

**Comment by mattboy9921** [comment]
This comes from the current implementation of the Cloud command framework. They have introduced v2 but the plugin is still using v1.8. I'll be working on getting the new version implemented but it is not backwards compatible so I have to rewrite a lot.

**Comment by enigma072485** [comment]
Ah. Gotcha... thank you for letting me know. I really appreciate the information. I look forward to the future of your plugins. 😄

**Comment by mattboy9921** [comment]
I'll actually keep this open as a way to track the update to Cloud 2!
